import json
import os

notebook = {
 'cells': [
  {
   'cell_type': 'markdown',
   'metadata': {},
   'source': [
    '# 1. Data Loading & Preprocessing\n',
    '\n',
    'For this project, we are utilizing the rich **StatsBomb dataset**, which includes high-resolution event data coupled with **StatsBomb 360-degree tracking data**. This 360 data provides a "freeze-frame" of player locations at the exact moment an action occurs, which is crucial for evaluating spatial control and context. We fetch this directly from the StatsBomb API using `statsbombpy`, pulling a match from the 2022 FIFA World Cup Final (Argentina vs France).'
   ]
  },
  {
   'cell_type': 'code',
   'execution_count': None,
   'metadata': {},
   'outputs': [],
   'source': [
    'import pandas as pd\n',
    'import numpy as np\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    'from mplsoccer import Pitch, VerticalPitch\n',
    'from statsbombpy import sb\n',
    'import warnings\n',
    'warnings.filterwarnings(\'ignore\')\n',
    '\n',
    '# Fetch data for the 2022 World Cup Final (Argentina vs France) which has 360 data.\n',
    'match_id = 3869151\n',
    '\n',
    'print(f"Fetching events for match_id: {match_id}...")\n',
    'events_df = sb.events(match_id=match_id)\n',
    '\n',
    'print(f"Fetching 360 frames for match_id: {match_id}...")\n',
    '# Fetching as dict to avoid pandas concatenation issues with duplicated index in older statsbombpy versions\n',
    'frames_list = sb.frames(match_id=match_id, fmt="dict")\n',
    'frames_df = pd.DataFrame(frames_list)\n',
    'frames_df = frames_df.rename(columns={"freeze_frame": "360_frames"})\n',
    '\n',
    '# Merge events with their corresponding 360 tracking frames\n',
    'df = pd.merge(events_df, frames_df[["event_uuid", "360_frames"]], left_on="id", right_on="event_uuid", how="left")\n',
    '\n',
    '# Filter for open-play passes and shots\n',
    '# We only care about events with spatial data (location)\n',
    'df = df[df["location"].notna()].copy()\n',
    '\n',
    'events_filtered = df[\n',
    '    (df["type"].isin(["Pass", "Shot"])) & \n',
    '    (~df["pass_type"].isin(["Free Kick", "Corner", "Throw-in", "Goal Kick"])) &\n',
    '    (~df["shot_type"].isin(["Penalty", "Free Kick"]))\n',
    '].copy()\n',
    '\n',
    '# Ensure target columns exist if some are missing for this specific match\n',
    'if "under_pressure" not in events_filtered.columns:\n',
    '    events_filtered["under_pressure"] = False\n',
    'if "shot_statsbomb_xg" not in events_filtered.columns:\n',
    '    events_filtered["shot_statsbomb_xg"] = 0.0\n',
    '\n',
    '# Discretize continuous coordinates (120x80) to a 16x12 grid\n',
    'grid_x_bins = 16\n',
    'grid_y_bins = 12\n',
    'pitch_length = 120.0\n',
    'pitch_width = 80.0\n',
    '\n',
    'def get_grid_cell(coord, max_val, bins):\n',
    '    if not isinstance(coord, list) or len(coord) < 2:\n',
    '        return np.nan, np.nan\n',
    '    x, y = coord[0], coord[1]\n',
    '    x_idx = min(int(x / (pitch_length / bins)), bins - 1)\n',
    '    y_idx = min(int(y / (pitch_width / bins)), bins - 1)\n',
    '    return x_idx, y_idx\n',
    '\n',
    '# Map start and end locations to the grid\n',
    'events_filtered[["start_x_idx", "start_y_idx"]] = pd.DataFrame(\n',
    '    events_filtered["location"].apply(lambda c: get_grid_cell(c, pitch_length, grid_x_bins)).tolist(), \n',
    '    index=events_filtered.index\n',
    ')\n',
    '\n',
    '# For passes, map end locations\n',
    'passes = events_filtered[events_filtered["type"] == "Pass"].copy()\n',
    'passes[["end_x_idx", "end_y_idx"]] = pd.DataFrame(\n',
    '    passes["pass_end_location"].apply(lambda c: get_grid_cell(c, pitch_length, grid_x_bins)).tolist(), \n',
    '    index=passes.index\n',
    ')\n',
    '\n',
    'passes[["type", "player", "location", "pass_end_location", "under_pressure", "360_frames"]].head()'
   ]
  },
  {
   'cell_type': 'markdown',
   'metadata': {},
   'source': [
    '# 2. Exploratory Data Analysis (Context & Spatial Architecture)\n',
    '\n',
    'Traditional event data points only tell us *what* happened and *where*, but they lack crucial defensive context. A 10-yard pass backwards is mathematically identical in raw event logs whether the player is in acres of space or surrounded by three defenders. To properly evaluate pass difficulty and a player\'s spatial awareness, we must visualize spatial control using the 360-degree tracking data, revealing the defensive structure the player had to bypass. Furthermore, constructing a team Passing Network helps us identify central playmaking hubs and understand the flow of possession.'
   ]
  },
  {
   'cell_type': 'code',
   'execution_count': None,
   'metadata': {},
   'outputs': [],
   'source': [
    '# --- A) Passing Network ---\n',
    'if "player" in passes.columns and "pass_recipient" in passes.columns:\n',
    '    # Filter for a specific team (taking the most frequent team as an example)\n',
    '    top_team = passes["team"].mode()[0] if "team" in passes.columns else passes.iloc[0]["team"]\n',
    '    team_passes = passes[passes["team"] == top_team].copy()\n',
    '    \n',
    '    # Calculate average location and pass counts\n',
    '    team_passes["x"] = team_passes["location"].apply(lambda l: l[0] if isinstance(l, list) else np.nan)\n',
    '    team_passes["y"] = team_passes["location"].apply(lambda l: l[1] if isinstance(l, list) else np.nan)\n',
    '    \n',
    '    avg_locations = team_passes.groupby("player")[["x", "y"]].mean()\n',
    '    pass_counts = team_passes.groupby(["player", "pass_recipient"]).size().reset_index(name="count")\n',
    '    pass_counts = pass_counts[pass_counts["count"] > 2] # Filter low-volume links\n',
    '    \n',
    '    # Draw Passing Network Pitch\n',
    '    pitch = Pitch(pitch_type="statsbomb", pitch_color="#22312b", line_color="#c7d5cc")\n',
    '    fig, ax = pitch.draw(figsize=(10, 7))\n',
    '    \n',
    '    # Draw lines (edges)\n',
    '    for _, row in pass_counts.iterrows():\n',
    '        passer = row["player"]\n',
    '        recipient = row["pass_recipient"]\n',
    '        if passer in avg_locations.index and recipient in avg_locations.index:\n',
    '            pitch.lines(avg_locations.loc[passer, "x"], avg_locations.loc[passer, "y"],\n',
    '                        avg_locations.loc[recipient, "x"], avg_locations.loc[recipient, "y"],\n',
    '                        lw=row["count"]*0.5, color="white", zorder=1, ax=ax, alpha=0.5)\n',
    '            \n',
    '    # Draw nodes\n',
    '    pitch.scatter(avg_locations["x"], avg_locations["y"], s=300, color="red", edgecolors="black", zorder=2, ax=ax)\n',
    '    \n',
    '    for player_name, row in avg_locations.iterrows():\n',
    '        player_label = str(player_name).split()[-1] if pd.notna(player_name) else ""\n',
    '        pitch.annotate(player_label, xy=(row["x"], row["y"] - 2), c="white", va="center", ha="center", size=10, zorder=3, ax=ax)\n',
    '        \n',
    '    ax.set_title(f"Passing Network: {top_team}", color="black", size=16)\n',
    '    plt.show()\n',
    '\n',
    '# --- B) 360 Freeze Frame ---\n',
    '# Find a pass under pressure with 360 frames\n',
    'if "under_pressure" in passes.columns and "360_frames" in passes.columns:\n',
    '    pressure_passes = passes[(passes["under_pressure"] == True) & (passes["360_frames"].notna())]\n',
    '    \n',
    '    if not pressure_passes.empty:\n',
    '        sample_pass = pressure_passes.iloc[0]\n',
    '        frames = sample_pass["360_frames"]\n',
    '        \n',
    '        pitch = Pitch(pitch_type="statsbomb", pitch_color="#22312b", line_color="#c7d5cc")\n',
    '        fig, ax = pitch.draw(figsize=(10, 7))\n',
    '        \n',
    '        # Plot player locations from 360 frame\n',
    '        teammate_x, teammate_y = [], []\n',
    '        opponent_x, opponent_y = [], []\n',
    '        \n',
    '        for p in frames:\n',
    '            if isinstance(p, dict) and "location" in p and "teammate" in p:\n',
    '                if p["teammate"]:\n',
    '                    teammate_x.append(p["location"][0])\n',
    '                    teammate_y.append(p["location"][1])\n',
    '                else:\n',
    '                    opponent_x.append(p["location"][0])\n',
    '                    opponent_y.append(p["location"][1])\n',
    '                    \n',
    '        # Teammates (blue) and Opponents (red)\n',
    '        pitch.scatter(teammate_x, teammate_y, s=150, color="blue", edgecolors="black", zorder=2, ax=ax, label="Teammates")\n',
    '        pitch.scatter(opponent_x, opponent_y, s=150, color="red", edgecolors="black", zorder=2, ax=ax, label="Opponents")\n',
    '        \n',
    '        # Plot the pass itself\n',
    '        px, py = sample_pass["location"]\n',
    '        ex, ey = sample_pass["pass_end_location"]\n',
    '        pitch.arrows(px, py, ex, ey, width=2, headwidth=10, color="yellow", zorder=3, ax=ax, label="Pass")\n',
    '        \n',
    '        ax.set_title("360 Freeze Frame: Pass Under Pressure", color="black", size=16)\n',
    '        ax.legend(loc="lower left")\n',
    '        plt.show()\n'
   ]
  },
  {
   'cell_type': 'markdown',
   'metadata': {},
   'source': [
    '# 3. Mathematical Modeling: The Markovian Expected Threat (xT) Surface\n',
    '\n',
    'To move away from outcome-biased models that only credit goals and assists, we implement a Markov Chain framework inspired by Sarah Rudd and Karun Singh. We divide the pitch into a 16x12 grid, treating each zone as a distinct "state." Instead of evaluating isolated actions, this model calculates the probability of scoring from any specific zone by looking N actions ahead (modeling football as a series of transitions between spatial states). \n',
    '\n',
    'We define the Expected Threat ($xT$) of a zone as the probability of scoring from that zone either directly via a shot, or indirectly by moving the ball to another zone. Mathematically, this is expressed as $xT_{x,y} = s_{x,y} \\times g_{x,y} + m_{x,y} \\times \\sum_{z,w} T_{(x,y) \\rightarrow (z,w)} xT_{z,w}$. \n',
    'To solve for the $xT$ surface efficiently, we express this system of equations in matrix form and use a linear algebra approach ($X = S + MTX$), utilizing NumPy to calculate the stable $xT$ value for every zone on the pitch simultaneously.'
   ]
  },
  {
   'cell_type': 'code',
   'execution_count': None,
   'metadata': {},
   'outputs': [],
   'source': [
    'n_zones = grid_x_bins * grid_y_bins\n',
    '\n',
    '# Initialize counting arrays\n',
    'shot_count = np.zeros((grid_x_bins, grid_y_bins))\n',
    'goal_count = np.zeros((grid_x_bins, grid_y_bins))\n',
    'move_count = np.zeros((grid_x_bins, grid_y_bins))\n',
    'transition_count = np.zeros((n_zones, n_zones))\n',
    '\n',
    '# Populate counts from events\n',
    'for _, event in events_filtered.iterrows():\n',
    '    if pd.isna(event.get("start_x_idx")) or pd.isna(event.get("start_y_idx")):\n',
    '        continue\n',
    '        \n',
    '    sx = int(event["start_x_idx"])\n',
    '    sy = int(event["start_y_idx"])\n',
    '    \n',
    '    if event["type"] == "Shot":\n',
    '        shot_count[sx, sy] += 1\n',
    '        # Check if shot was a goal (StatsBomb uses "shot_outcome" == "Goal")\n',
    '        if event.get("shot_outcome") == "Goal":\n',
    '            goal_count[sx, sy] += 1\n',
    '            \n',
    '    elif event["type"] == "Pass":\n',
    '        move_count[sx, sy] += 1\n',
    '        if not pd.isna(event.get("end_x_idx")) and not pd.isna(event.get("end_y_idx")):\n',
    '            ex = int(event["end_x_idx"])\n',
    '            ey = int(event["end_y_idx"])\n',
    '            # Calculate flat indices for the 192x192 transition matrix\n',
    '            start_idx = sx * grid_y_bins + sy\n',
    '            end_idx = ex * grid_y_bins + ey\n',
    '            transition_count[start_idx, end_idx] += 1\n',
    '\n',
    '# Calculate probabilities\n',
    'total_actions = shot_count + move_count\n',
    '# Avoid division by zero\n',
    'safe_actions = np.where(total_actions == 0, 1, total_actions)\n',
    'safe_shots = np.where(shot_count == 0, 1, shot_count)\n',
    '\n',
    '# s_{x,y}: Probability of shooting from (x,y)\n',
    's_prob = shot_count / safe_actions\n',
    '# g_{x,y}: Probability of scoring given a shot from (x,y)\n',
    'g_prob = goal_count / safe_shots\n',
    '# m_{x,y}: Probability of moving the ball from (x,y)\n',
    'm_prob = move_count / safe_actions\n',
    '\n',
    '# S vector: Base probability of scoring directly (flattened)\n',
    'S = (s_prob * g_prob).flatten()\n',
    '\n',
    '# T matrix: Transition probabilities (row-normalized)\n',
    'row_sums = transition_count.sum(axis=1)\n',
    'safe_row_sums = np.where(row_sums == 0, 1, row_sums)\n',
    'T = transition_count / safe_row_sums[:, np.newaxis]\n',
    '\n',
    '# Create the M diagonal matrix\n',
    'M = np.diag(m_prob.flatten())\n',
    '\n',
    '# Linear algebra approach to solve for X: X = S + M * T * X  =>  (I - M * T) * X = S\n',
    'I = np.eye(n_zones)\n',
    'try:\n',
    '    X = np.linalg.solve(I - np.dot(M, T), S)\n',
    'except np.linalg.LinAlgError:\n',
    '    # Fallback to pseudo-inverse if singular\n',
    '    X = np.dot(np.linalg.pinv(I - np.dot(M, T)), S)\n',
    '\n',
    '# Reshape back to grid\n',
    'xT_surface = X.reshape((grid_x_bins, grid_y_bins))\n',
    '\n',
    '# Visualize xT surface\n',
    'pitch = Pitch(pitch_type="statsbomb", line_zorder=2, pitch_color="#22312b", line_color="#efefef")\n',
    'fig, ax = pitch.draw(figsize=(10, 7))\n',
    '\n',
    'import matplotlib.colors as mcolors\n',
    'cmap = plt.cm.get_cmap("magma")\n',
    'heatmap = pitch.heatmap(xT_surface.T, ax=ax, cmap=cmap, alpha=0.8)\n',
    '\n',
    '# Add colorbar\n',
    'cbar = fig.colorbar(heatmap, ax=ax, shrink=0.6)\n',
    'cbar.set_label("Expected Threat (xT)")\n',
    '\n',
    'ax.set_title("Markovian Expected Threat (xT) Surface", color="black", size=16)\n',
    'plt.show()\n'
   ]
  },
  {
   'cell_type': 'markdown',
   'metadata': {},
   'source': [
    '# 4. Action Valuation: Solving the FIFA Paradox\n',
    '\n',
    'With the foundational spatial model built, we can now distribute appropriate credit to players. The fundamental concept of Expected Threat is that a player\'s action is valuable if it moves the team from a state of lower goal-scoring probability to a state of higher probability.\n',
    '\n',
    'Therefore, the value added by any given pass or progression is simply the difference in the Expected Threat of the end location and the start location: $xT_{added} = xT_{end} - xT_{start}$. This elegantly solves the FIFA Paradox: a deep-lying playmaker who consistently bypasses defensive blocks to move the ball into dangerous zones receives high $xT_{added}$ credit, regardless of whether the striker subsequently scores or misses the final shot.'
   ]
  },
  {
   'cell_type': 'code',
   'execution_count': None,
   'metadata': {},
   'outputs': [],
   'source': [
    'def calculate_xt_added(row):\n',
    '    if pd.isna(row.get("start_x_idx")) or pd.isna(row.get("end_x_idx")):\n',
    '        return np.nan\n',
    '        \n',
    '    sx = int(row["start_x_idx"])\n',
    '    sy = int(row["start_y_idx"])\n',
    '    ex = int(row["end_x_idx"])\n',
    '    ey = int(row["end_y_idx"])\n',
    '    \n',
    '    # Check if indices are within bounds\n',
    '    if 0 <= sx < grid_x_bins and 0 <= sy < grid_y_bins and 0 <= ex < grid_x_bins and 0 <= ey < grid_y_bins:\n',
    '        xt_start = xT_surface[sx, sy]\n',
    '        xt_end = xT_surface[ex, ey]\n',
    '        return xt_end - xt_start\n',
    '    return np.nan\n',
    '\n',
    '# Calculate xT added for passes\n',
    'passes["xT_added"] = passes.apply(calculate_xt_added, axis=1)\n',
    '\n',
    '# Preview passes with their new xT values\n',
    'passes[["player", "type", "start_x_idx", "start_y_idx", "end_x_idx", "end_y_idx", "xT_added"]].head(10)\n'
   ]
  },
  {
   'cell_type': 'markdown',
   'metadata': {},
   'source': [
    '# 5. Synthesizing the Unified Performance Index (UPI)\n',
    '\n',
    'We conclude our analysis by synthesizing the Unified Performance Index (UPI). The UPI aggregates these mathematically derived state-values over a match or season to provide a holistic view of a player\'s impact. \n',
    '\n',
    'By summing the total $xT_{added}$ for each player, we construct the On-Ball contribution metric of the UPI. Players who consistently execute actions that move the ball from low-threat areas to high-threat areas—especially when executing line-breaking passes under pressure—accumulate the highest ratings. This directly quantifies and proves the "invisible" tactical value of elite playmakers, midfielders, and progressive defenders who are traditionally overlooked by outcome-biased metrics.'
   ]
  },
  {
   'cell_type': 'code',
   'execution_count': None,
   'metadata': {},
   'outputs': [],
   'source': [
    '# Group by player and aggregate xT and pass volume\n',
    'player_upi = passes.groupby("player").agg(\n',
    '    total_xT_added=("xT_added", "sum"),\n',
    '    pass_count=("xT_added", "count")\n',
    ').reset_index()\n',
    '\n',
    '# Filter for players with a significant number of passes (e.g., at least 5 passes since it\'s a single match)\n',
    'min_passes_threshold = 5\n',
    'qualified_players = player_upi[player_upi["pass_count"] >= min_passes_threshold].copy()\n',
    '\n',
    '# Sort by total xT added to find the top performers\n',
    'top_10_upi = qualified_players.sort_values(by="total_xT_added", ascending=False).head(10)\n',
    '\n',
    '# Rename column for final presentation\n',
    'top_10_upi = top_10_upi.rename(columns={"total_xT_added": "On-Ball UPI (C_on-ball)"})\n',
    '\n',
    '# Plotting the Bar Chart\n',
    'plt.figure(figsize=(12, 7))\n',
    'sns.barplot(\n',
    '    data=top_10_upi, \n',
    '    x="On-Ball UPI (C_on-ball)", \n',
    '    y="player", \n',
    '    palette="viridis"\n',
    ')\n',
    '\n',
    'plt.title("Top 10 Players by On-Ball UPI Contribution", fontsize=16)\n',
    'plt.xlabel("Total Expected Threat (xT) Added", fontsize=12)\n',
    'plt.ylabel("Player Name", fontsize=12)\n',
    'plt.grid(axis="x", linestyle="--", alpha=0.7)\n',
    'plt.tight_layout()\n',
    'plt.show()\n',
    '\n',
    '# Display styled dataframe\n',
    'top_10_upi.style.background_gradient(cmap="viridis", subset=["On-Ball UPI (C_on-ball)"])\n'
   ]
  }
 ],
 'metadata': {
  'kernelspec': {
   'display_name': 'Python 3',
   'language': 'python',
   'name': 'python3'
  },
  'language_info': {
   'codemirror_mode': {
    'name': 'ipython',
    'version': 3
   },
   'file_extension': '.py',
   'mimetype': 'text/x-python',
   'name': 'python',
   'nbconvert_exporter': 'python',
   'pygments_lexer': 'ipython3',
   'version': '3.8.0'
  }
 },
 'nbformat': 4,
 'nbformat_minor': 4
}

with open('UPI_Final_Report.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1)
